extends: semistandard
parserOptions:
  ecmaVersion: 5
  sourceType: script
env:
  es6: false
  node: false
  browser: true
rules:
  block-scoped-var: "error"
  no-use-before-define: "error"
  no-var: "off"
  no-shadow: [ "error", { "hoist": "all" } ]
